#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/siskojaya/siskojaya /usr/bin/siskojaya

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/siskojaya.service ]; then
			rm /etc/systemd/system/siskojaya.service /usr/lib/systemd/system/siskojaya.service /usr/lib/systemd/user/siskojaya.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/siskojaya/files/systemd/siskojaya.service /usr/lib/systemd/system/siskojaya.service
		# try fix error in Ubuntu 18.04
		# Failed to reload siskojaya.service: Unit siskojaya.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/siskojaya.service:10: Executable path is not absolute: pkill -f "siskojaya --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/siskojaya.service
		fi
		systemctl daemon-reload
		systemctl enable siskojaya
		systemctl start siskojaya
	fi
fi
